# Generated by Django 3.2.4 on 2021-06-28 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='bith_date',
            new_name='birth_date',
        ),
    ]
