# Generated by Django 3.2.4 on 2021-06-28 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_rename_bith_date_customer_birth_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='second_name',
            new_name='last_name',
        ),
    ]
