# Generated by Django 3.2.4 on 2021-06-29 05:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_rename_second_name_customer_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='file',
            field=models.FileField(upload_to='', validators=[django.core.validators.FileExtensionValidator(['xlsx'])]),
        ),
    ]
